version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 9082:80
    volumes:
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_config/conf.d/:/etc/nginx/conf.d/
      - ./nginx_logs/:/var/log/nginx/
      - ./html/:/usr/app/
  app:
    build: .
    volumes:
      - .:/app